[phases.setup]
nixPkgs = ['protobuf', 'git']

[phases.build]
cmds = [
    'echo "Building nodelink server..."',
    'chmod +x generate.sh',
    './generate.sh',
    'cd server',
    'go build -o main ./cmd/server'
]

[start]
cmd = 'cd server && ./main'

[variables]
CGO_ENABLED = "0"
GOOS = "linux"
GOARCH = "amd64"
