[build]
builder = "nixpacks"

[deploy]
startCommand = "./main"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"

[env]
# Railway will automatically provide PORT
# Add any other environment variables you need
GRPC_PORT = "9090"
