[phases.setup]
nixPkgs = ["go_1_21"]

[phases.build]
cmds = [
  "go work init",
  "go work use ./proto",
  "go work use ./server",
  "cd server && go build -ldflags='-w -s' -o main cmd/server/main.go"
]

[variables]
GO_VERSION = "1.23"

[phases.setup]
nixPkgs = ["go_1_23"]

[phases.install]
cmds = [
    # Download dependencies for all modules
    "go mod download || echo 'Root mod download failed'",
    "cd proto && go mod download",
    "cd server && go mod download"
]

[phases.build] 
cmds = [
    # Build the server binary
    "cd server && go build -ldflags='-w -s' -o out cmd/server/main.go"
]

[start]
cmd = "cd server && ./out"
