[build]
builder = "DOCKERFILE"
dockerfilePath = "server/Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Railway will build from the repository root, not the server subdirectory
[variables]
# Railway will automatically set PORT for the HTTP server
# GRPC_PORT can be customized if needed
