// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: event.proto

package eventstream

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventResponse_Status int32

const (
	EventResponse_UNKNOWN     EventResponse_Status = 0
	EventResponse_SUCCESS     EventResponse_Status = 1
	EventResponse_FAILURE     EventResponse_Status = 2
	EventResponse_IN_PROGRESS EventResponse_Status = 3
)

// Enum value maps for EventResponse_Status.
var (
	EventResponse_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "SUCCESS",
		2: "FAILURE",
		3: "IN_PROGRESS",
	}
	EventResponse_Status_value = map[string]int32{
		"UNKNOWN":     0,
		"SUCCESS":     1,
		"FAILURE":     2,
		"IN_PROGRESS": 3,
	}
)

func (x EventResponse_Status) Enum() *EventResponse_Status {
	p := new(EventResponse_Status)
	*p = x
	return p
}

func (x EventResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[0].Descriptor()
}

func (EventResponse_Status) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[0]
}

func (x EventResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventResponse_Status.Descriptor instead.
func (EventResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{2, 0}
}

type ServerToNodeEvent struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	EventId string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	AgentId string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Types that are valid to be assigned to Task:
	//
	//	*ServerToNodeEvent_ShellExecute
	//	*ServerToNodeEvent_DockerOperation
	//	*ServerToNodeEvent_LogMessage
	Task          isServerToNodeEvent_Task `protobuf_oneof:"task"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerToNodeEvent) Reset() {
	*x = ServerToNodeEvent{}
	mi := &file_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerToNodeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerToNodeEvent) ProtoMessage() {}

func (x *ServerToNodeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerToNodeEvent.ProtoReflect.Descriptor instead.
func (*ServerToNodeEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

func (x *ServerToNodeEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ServerToNodeEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ServerToNodeEvent) GetTask() isServerToNodeEvent_Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *ServerToNodeEvent) GetShellExecute() *ShellExecute {
	if x != nil {
		if x, ok := x.Task.(*ServerToNodeEvent_ShellExecute); ok {
			return x.ShellExecute
		}
	}
	return nil
}

func (x *ServerToNodeEvent) GetDockerOperation() *DockerOperation {
	if x != nil {
		if x, ok := x.Task.(*ServerToNodeEvent_DockerOperation); ok {
			return x.DockerOperation
		}
	}
	return nil
}

func (x *ServerToNodeEvent) GetLogMessage() *LogMessage {
	if x != nil {
		if x, ok := x.Task.(*ServerToNodeEvent_LogMessage); ok {
			return x.LogMessage
		}
	}
	return nil
}

type isServerToNodeEvent_Task interface {
	isServerToNodeEvent_Task()
}

type ServerToNodeEvent_ShellExecute struct {
	ShellExecute *ShellExecute `protobuf:"bytes,3,opt,name=shell_execute,json=shellExecute,proto3,oneof"`
}

type ServerToNodeEvent_DockerOperation struct {
	DockerOperation *DockerOperation `protobuf:"bytes,4,opt,name=docker_operation,json=dockerOperation,proto3,oneof"`
}

type ServerToNodeEvent_LogMessage struct {
	LogMessage *LogMessage `protobuf:"bytes,5,opt,name=log_message,json=logMessage,proto3,oneof"`
}

func (*ServerToNodeEvent_ShellExecute) isServerToNodeEvent_Task() {}

func (*ServerToNodeEvent_DockerOperation) isServerToNodeEvent_Task() {}

func (*ServerToNodeEvent_LogMessage) isServerToNodeEvent_Task() {}

type NodeToServerEvent struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AgentId string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*NodeToServerEvent_LogMessage
	//	*NodeToServerEvent_EventResponse
	Event         isNodeToServerEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeToServerEvent) Reset() {
	*x = NodeToServerEvent{}
	mi := &file_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeToServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeToServerEvent) ProtoMessage() {}

func (x *NodeToServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeToServerEvent.ProtoReflect.Descriptor instead.
func (*NodeToServerEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

func (x *NodeToServerEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *NodeToServerEvent) GetEvent() isNodeToServerEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *NodeToServerEvent) GetLogMessage() *LogMessage {
	if x != nil {
		if x, ok := x.Event.(*NodeToServerEvent_LogMessage); ok {
			return x.LogMessage
		}
	}
	return nil
}

func (x *NodeToServerEvent) GetEventResponse() *EventResponse {
	if x != nil {
		if x, ok := x.Event.(*NodeToServerEvent_EventResponse); ok {
			return x.EventResponse
		}
	}
	return nil
}

type isNodeToServerEvent_Event interface {
	isNodeToServerEvent_Event()
}

type NodeToServerEvent_LogMessage struct {
	LogMessage *LogMessage `protobuf:"bytes,2,opt,name=log_message,json=logMessage,proto3,oneof"`
}

type NodeToServerEvent_EventResponse struct {
	EventResponse *EventResponse `protobuf:"bytes,3,opt,name=event_response,json=eventResponse,proto3,oneof"`
}

func (*NodeToServerEvent_LogMessage) isNodeToServerEvent_Event() {}

func (*NodeToServerEvent_EventResponse) isNodeToServerEvent_Event() {}

type EventResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	EventRef string                 `protobuf:"bytes,1,opt,name=event_ref,json=eventRef,proto3" json:"event_ref,omitempty"` // event_id from ServerToNodeEvent
	Status   EventResponse_Status   `protobuf:"varint,2,opt,name=status,proto3,enum=eventstream.EventResponse_Status" json:"status,omitempty"`
	// Types that are valid to be assigned to Response:
	//
	//	*EventResponse_Update
	//	*EventResponse_Result
	Response      isEventResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{2}
}

func (x *EventResponse) GetEventRef() string {
	if x != nil {
		return x.EventRef
	}
	return ""
}

func (x *EventResponse) GetStatus() EventResponse_Status {
	if x != nil {
		return x.Status
	}
	return EventResponse_UNKNOWN
}

func (x *EventResponse) GetResponse() isEventResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *EventResponse) GetUpdate() *EventResponseUpdate {
	if x != nil {
		if x, ok := x.Response.(*EventResponse_Update); ok {
			return x.Update
		}
	}
	return nil
}

func (x *EventResponse) GetResult() *EventResponseResult {
	if x != nil {
		if x, ok := x.Response.(*EventResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isEventResponse_Response interface {
	isEventResponse_Response()
}

type EventResponse_Update struct {
	Update *EventResponseUpdate `protobuf:"bytes,3,opt,name=update,proto3,oneof"`
}

type EventResponse_Result struct {
	Result *EventResponseResult `protobuf:"bytes,4,opt,name=result,proto3,oneof"`
}

func (*EventResponse_Update) isEventResponse_Response() {}

func (*EventResponse_Result) isEventResponse_Response() {}

type EventResponseUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *structpb.Struct       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResponseUpdate) Reset() {
	*x = EventResponseUpdate{}
	mi := &file_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponseUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponseUpdate) ProtoMessage() {}

func (x *EventResponseUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponseUpdate.ProtoReflect.Descriptor instead.
func (*EventResponseUpdate) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{3}
}

func (x *EventResponseUpdate) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type EventResponseResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *structpb.Struct       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResponseResult) Reset() {
	*x = EventResponseResult{}
	mi := &file_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponseResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponseResult) ProtoMessage() {}

func (x *EventResponseResult) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponseResult.ProtoReflect.Descriptor instead.
func (*EventResponseResult) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{4}
}

func (x *EventResponseResult) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type EventResponseProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Percent       int32                  `protobuf:"varint,1,opt,name=percent,proto3" json:"percent,omitempty"` // 0-100
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResponseProgress) Reset() {
	*x = EventResponseProgress{}
	mi := &file_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponseProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponseProgress) ProtoMessage() {}

func (x *EventResponseProgress) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponseProgress.ProtoReflect.Descriptor instead.
func (*EventResponseProgress) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{5}
}

func (x *EventResponseProgress) GetPercent() int32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *EventResponseProgress) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type ShellExecute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           string                 `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellExecute) Reset() {
	*x = ShellExecute{}
	mi := &file_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellExecute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellExecute) ProtoMessage() {}

func (x *ShellExecute) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellExecute.ProtoReflect.Descriptor instead.
func (*ShellExecute) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{6}
}

func (x *ShellExecute) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

type DockerOperation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Operation:
	//
	//	*DockerOperation_DockerRun
	//	*DockerOperation_DockerStart
	//	*DockerOperation_DockerStop
	//	*DockerOperation_DockerLogs
	Operation     isDockerOperation_Operation `protobuf_oneof:"operation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DockerOperation) Reset() {
	*x = DockerOperation{}
	mi := &file_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerOperation) ProtoMessage() {}

func (x *DockerOperation) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerOperation.ProtoReflect.Descriptor instead.
func (*DockerOperation) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{7}
}

func (x *DockerOperation) GetOperation() isDockerOperation_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *DockerOperation) GetDockerRun() *DockerRun {
	if x != nil {
		if x, ok := x.Operation.(*DockerOperation_DockerRun); ok {
			return x.DockerRun
		}
	}
	return nil
}

func (x *DockerOperation) GetDockerStart() *DockerStart {
	if x != nil {
		if x, ok := x.Operation.(*DockerOperation_DockerStart); ok {
			return x.DockerStart
		}
	}
	return nil
}

func (x *DockerOperation) GetDockerStop() *DockerStop {
	if x != nil {
		if x, ok := x.Operation.(*DockerOperation_DockerStop); ok {
			return x.DockerStop
		}
	}
	return nil
}

func (x *DockerOperation) GetDockerLogs() *DockerLogs {
	if x != nil {
		if x, ok := x.Operation.(*DockerOperation_DockerLogs); ok {
			return x.DockerLogs
		}
	}
	return nil
}

type isDockerOperation_Operation interface {
	isDockerOperation_Operation()
}

type DockerOperation_DockerRun struct {
	DockerRun *DockerRun `protobuf:"bytes,1,opt,name=docker_run,json=dockerRun,proto3,oneof"`
}

type DockerOperation_DockerStart struct {
	DockerStart *DockerStart `protobuf:"bytes,2,opt,name=docker_start,json=dockerStart,proto3,oneof"`
}

type DockerOperation_DockerStop struct {
	DockerStop *DockerStop `protobuf:"bytes,3,opt,name=docker_stop,json=dockerStop,proto3,oneof"`
}

type DockerOperation_DockerLogs struct {
	DockerLogs *DockerLogs `protobuf:"bytes,4,opt,name=docker_logs,json=dockerLogs,proto3,oneof"`
}

func (*DockerOperation_DockerRun) isDockerOperation_Operation() {}

func (*DockerOperation_DockerStart) isDockerOperation_Operation() {}

func (*DockerOperation_DockerStop) isDockerOperation_Operation() {}

func (*DockerOperation_DockerLogs) isDockerOperation_Operation() {}

type DockerRun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Img           string                 `protobuf:"bytes,1,opt,name=img,proto3" json:"img,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DockerRun) Reset() {
	*x = DockerRun{}
	mi := &file_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerRun) ProtoMessage() {}

func (x *DockerRun) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerRun.ProtoReflect.Descriptor instead.
func (*DockerRun) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{8}
}

func (x *DockerRun) GetImg() string {
	if x != nil {
		return x.Img
	}
	return ""
}

type DockerStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DockerStart) Reset() {
	*x = DockerStart{}
	mi := &file_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerStart) ProtoMessage() {}

func (x *DockerStart) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerStart.ProtoReflect.Descriptor instead.
func (*DockerStart) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{9}
}

func (x *DockerStart) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DockerStop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DockerStop) Reset() {
	*x = DockerStop{}
	mi := &file_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerStop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerStop) ProtoMessage() {}

func (x *DockerStop) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerStop.ProtoReflect.Descriptor instead.
func (*DockerStop) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{10}
}

func (x *DockerStop) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DockerLogs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DockerLogs) Reset() {
	*x = DockerLogs{}
	mi := &file_event_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerLogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerLogs) ProtoMessage() {}

func (x *DockerLogs) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerLogs.ProtoReflect.Descriptor instead.
func (*DockerLogs) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{11}
}

func (x *DockerLogs) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type LogMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogMessage) Reset() {
	*x = LogMessage{}
	mi := &file_event_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMessage) ProtoMessage() {}

func (x *LogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMessage.ProtoReflect.Descriptor instead.
func (*LogMessage) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{12}
}

func (x *LogMessage) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_event_proto protoreflect.FileDescriptor

const file_event_proto_rawDesc = "" +
	"\n" +
	"\vevent.proto\x12\veventstream\x1a\x1cgoogle/protobuf/struct.proto\"\x9a\x02\n" +
	"\x11ServerToNodeEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12@\n" +
	"\rshell_execute\x18\x03 \x01(\v2\x19.eventstream.ShellExecuteH\x00R\fshellExecute\x12I\n" +
	"\x10docker_operation\x18\x04 \x01(\v2\x1c.eventstream.DockerOperationH\x00R\x0fdockerOperation\x12:\n" +
	"\vlog_message\x18\x05 \x01(\v2\x17.eventstream.LogMessageH\x00R\n" +
	"logMessageB\x06\n" +
	"\x04task\"\xb8\x01\n" +
	"\x11NodeToServerEvent\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12:\n" +
	"\vlog_message\x18\x02 \x01(\v2\x17.eventstream.LogMessageH\x00R\n" +
	"logMessage\x12C\n" +
	"\x0eevent_response\x18\x03 \x01(\v2\x1a.eventstream.EventResponseH\x00R\reventResponseB\a\n" +
	"\x05event\"\xad\x02\n" +
	"\rEventResponse\x12\x1b\n" +
	"\tevent_ref\x18\x01 \x01(\tR\beventRef\x129\n" +
	"\x06status\x18\x02 \x01(\x0e2!.eventstream.EventResponse.StatusR\x06status\x12:\n" +
	"\x06update\x18\x03 \x01(\v2 .eventstream.EventResponseUpdateH\x00R\x06update\x12:\n" +
	"\x06result\x18\x04 \x01(\v2 .eventstream.EventResponseResultH\x00R\x06result\"@\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\v\n" +
	"\aFAILURE\x10\x02\x12\x0f\n" +
	"\vIN_PROGRESS\x10\x03B\n" +
	"\n" +
	"\bresponse\"B\n" +
	"\x13EventResponseUpdate\x12+\n" +
	"\x04data\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x04data\"B\n" +
	"\x13EventResponseResult\x12+\n" +
	"\x04data\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x04data\"I\n" +
	"\x15EventResponseProgress\x12\x18\n" +
	"\apercent\x18\x01 \x01(\x05R\apercent\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\" \n" +
	"\fShellExecute\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\tR\x03cmd\"\x8e\x02\n" +
	"\x0fDockerOperation\x127\n" +
	"\n" +
	"docker_run\x18\x01 \x01(\v2\x16.eventstream.DockerRunH\x00R\tdockerRun\x12=\n" +
	"\fdocker_start\x18\x02 \x01(\v2\x18.eventstream.DockerStartH\x00R\vdockerStart\x12:\n" +
	"\vdocker_stop\x18\x03 \x01(\v2\x17.eventstream.DockerStopH\x00R\n" +
	"dockerStop\x12:\n" +
	"\vdocker_logs\x18\x04 \x01(\v2\x17.eventstream.DockerLogsH\x00R\n" +
	"dockerLogsB\v\n" +
	"\toperation\"\x1d\n" +
	"\tDockerRun\x12\x10\n" +
	"\x03img\x18\x01 \x01(\tR\x03img\"\x1d\n" +
	"\vDockerStart\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1c\n" +
	"\n" +
	"DockerStop\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1c\n" +
	"\n" +
	"DockerLogs\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1e\n" +
	"\n" +
	"LogMessage\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg2b\n" +
	"\fEventService\x12R\n" +
	"\fStreamEvents\x12\x1e.eventstream.NodeToServerEvent\x1a\x1e.eventstream.ServerToNodeEvent(\x010\x01B0Z.github.com/mooncorn/nodelink/proto/eventstreamb\x06proto3"

var (
	file_event_proto_rawDescOnce sync.Once
	file_event_proto_rawDescData []byte
)

func file_event_proto_rawDescGZIP() []byte {
	file_event_proto_rawDescOnce.Do(func() {
		file_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)))
	})
	return file_event_proto_rawDescData
}

var file_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_event_proto_goTypes = []any{
	(EventResponse_Status)(0),     // 0: eventstream.EventResponse.Status
	(*ServerToNodeEvent)(nil),     // 1: eventstream.ServerToNodeEvent
	(*NodeToServerEvent)(nil),     // 2: eventstream.NodeToServerEvent
	(*EventResponse)(nil),         // 3: eventstream.EventResponse
	(*EventResponseUpdate)(nil),   // 4: eventstream.EventResponseUpdate
	(*EventResponseResult)(nil),   // 5: eventstream.EventResponseResult
	(*EventResponseProgress)(nil), // 6: eventstream.EventResponseProgress
	(*ShellExecute)(nil),          // 7: eventstream.ShellExecute
	(*DockerOperation)(nil),       // 8: eventstream.DockerOperation
	(*DockerRun)(nil),             // 9: eventstream.DockerRun
	(*DockerStart)(nil),           // 10: eventstream.DockerStart
	(*DockerStop)(nil),            // 11: eventstream.DockerStop
	(*DockerLogs)(nil),            // 12: eventstream.DockerLogs
	(*LogMessage)(nil),            // 13: eventstream.LogMessage
	(*structpb.Struct)(nil),       // 14: google.protobuf.Struct
}
var file_event_proto_depIdxs = []int32{
	7,  // 0: eventstream.ServerToNodeEvent.shell_execute:type_name -> eventstream.ShellExecute
	8,  // 1: eventstream.ServerToNodeEvent.docker_operation:type_name -> eventstream.DockerOperation
	13, // 2: eventstream.ServerToNodeEvent.log_message:type_name -> eventstream.LogMessage
	13, // 3: eventstream.NodeToServerEvent.log_message:type_name -> eventstream.LogMessage
	3,  // 4: eventstream.NodeToServerEvent.event_response:type_name -> eventstream.EventResponse
	0,  // 5: eventstream.EventResponse.status:type_name -> eventstream.EventResponse.Status
	4,  // 6: eventstream.EventResponse.update:type_name -> eventstream.EventResponseUpdate
	5,  // 7: eventstream.EventResponse.result:type_name -> eventstream.EventResponseResult
	14, // 8: eventstream.EventResponseUpdate.data:type_name -> google.protobuf.Struct
	14, // 9: eventstream.EventResponseResult.data:type_name -> google.protobuf.Struct
	9,  // 10: eventstream.DockerOperation.docker_run:type_name -> eventstream.DockerRun
	10, // 11: eventstream.DockerOperation.docker_start:type_name -> eventstream.DockerStart
	11, // 12: eventstream.DockerOperation.docker_stop:type_name -> eventstream.DockerStop
	12, // 13: eventstream.DockerOperation.docker_logs:type_name -> eventstream.DockerLogs
	2,  // 14: eventstream.EventService.StreamEvents:input_type -> eventstream.NodeToServerEvent
	1,  // 15: eventstream.EventService.StreamEvents:output_type -> eventstream.ServerToNodeEvent
	15, // [15:16] is the sub-list for method output_type
	14, // [14:15] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	file_event_proto_msgTypes[0].OneofWrappers = []any{
		(*ServerToNodeEvent_ShellExecute)(nil),
		(*ServerToNodeEvent_DockerOperation)(nil),
		(*ServerToNodeEvent_LogMessage)(nil),
	}
	file_event_proto_msgTypes[1].OneofWrappers = []any{
		(*NodeToServerEvent_LogMessage)(nil),
		(*NodeToServerEvent_EventResponse)(nil),
	}
	file_event_proto_msgTypes[2].OneofWrappers = []any{
		(*EventResponse_Update)(nil),
		(*EventResponse_Result)(nil),
	}
	file_event_proto_msgTypes[7].OneofWrappers = []any{
		(*DockerOperation_DockerRun)(nil),
		(*DockerOperation_DockerStart)(nil),
		(*DockerOperation_DockerStop)(nil),
		(*DockerOperation_DockerLogs)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		EnumInfos:         file_event_proto_enumTypes,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}
