name: Deploy Frontend to Heroku
on:
  push:
    branches: [main]
    paths:
      - 'client/**'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies and build
        run: |
          cd client
          npm i
          npm run build
      - name: Add built files to git
        run: |
          git add client/dist -f
          git commit -m "Add built frontend for deployment" --allow-empty
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh
      - uses: akhileshns/heroku-deploy@v3.14.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{vars.HEROKU_CLIENT_APP_NAME}}
          heroku_email: ${{vars.HEROKU_EMAIL}}
          appdir: client


