name: Deploy Frontend to Heroku
on:
  push:
    branches: [main]
    paths:
      - 'client/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Heroku
        run: |
          cd client
          heroku git:remote -a my-react-app
          git push heroku main 
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}